project:
  type: website

website:
  title: "Alex Clare"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: about.qmd
        text: Projects
  
  page-footer: 
    right: "&copy; 2024, Alex Clare"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto